// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://gdynwkwqfesubalfphre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkeW53a3dxZmVzdWJhbGZwaHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODk1MjQsImV4cCI6MjA3MjQ2NTUyNH0.iS--Yh_PR1PbknQvuKZR9vH7y54271HPFFymAIyPORo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);